---
title: "AI Alone Won’t Save Data Quality: Lessons from The Financial Markets"
author: Tyler J. Brough
format: gfm
---

## AI Alone Won’t Save Data Quality: Lessons from The Financial Markets

**Outline**

1. [Who am I?](https://github.com/broughtj)
  - Finance PhD, DAIS Dept. at USU
  - Scholarly efforts in FinTech and ***Computational Statistical Catallactics***
2. Michael Jordan and "AI, the revolution that hasn't happened yet!"
  - Data science is a new engineering discipline founded upon CS, Stats, and ***ECON***!!!
  - Not human imatative, but human augmentative and intelligent infrastructure
3. Between Two Nobels: Buchanan & Hayek
  - Catallactics: economics as a humane science 
  - *The science of exchange*, *to admit into the community* *to turn an outsider into a friend*
  - The evolution of institutions as attempts to cope with knowledge/coordination problems
  - [I and Thou](https://link.springer.com/article/10.1007/s11127-023-01047-y)
4. Institutions that attempt to solve two problems: 1) knowledge problems, 2) coordination problems
  - Hayek (1937), (1945) and Buchanan (1964)
  - The *price mechanism* is a *wonder* that results from human action, but not human design
5. Jeffrey Williams and the *Origin of Futures Markets*
  - Futures contracts allow for intertemporal coordination via price mechanism
  - Richard Roll on [orange juice and weather](https://www.jstor.org/stable/549?seq=1)
  - Case of upstate NY breadstuffs
  - Default and settlement without resort to court system
6. Programmatic Sample
  - What are the knowledge problems?
  - What are the coordination problems?
  - Enshittification? No! 
  - A *humane* data science requires proper *exchange* relationships

